### PR TITLE
Update bot.php

### PR DESCRIPTION
**Pull request by RoshanHacker**

### CODE REVIEW

**Comment by Benchamxd** [comment]
What is this😂

**Comment by RoshanHacker** [comment]
Leave

**Comment by Benchamxd** [comment]
@RoshanHacker Ohk😂🚶‍♂👨‍🦯

**Comment by Adithyan1133-ctrl** [comment]
@Benchamxd 🥴

**Comment by Benchamxd** [comment]
@Adithyan1133-ctrl

**Comment by Benchamxd** [comment]
@Adithyan1133-ctrl 😂

**Pull request closed without merging**
